<?php
/**
 * TopSeo font icon option
 * @param $sets
 * @return mixed
 */

// ionicon
function topseo_font_icons($sets) {
    $sets['ionicon'] = array(
        'font-style-src' => get_template_directory_uri().'/css/ionicon.min.css',
        'container-class' => 'fa-lg', // some fonts need special wrapper class to display properly
        'groups' => array(
            'ion-icon' => esc_html__('Ion Icons', 'topseo'),
            'web-app' => esc_html__('Web Application Icons', 'topseo'),
            'transport' => esc_html__('Transportation Icons', 'topseo'),
            'gender' => esc_html__('Gender Icons', 'topseo'),
            'file' => esc_html__('File Type Icons', 'topseo'),
            'form' => esc_html__('Form Control Icons', 'topseo'),
            'payment' => esc_html__('Payment Icons', 'topseo'),
            'chart' => esc_html__('Chart Icons', 'topseo'),
            'currency' => esc_html__('Currency Icons', 'topseo'),
            'text' => esc_html__('Text Editor Icons', 'topseo'),
            'direction' => esc_html__('Directional Icons', 'topseo'),
            'video' => esc_html__('Video Player Icons', 'topseo'),
            'brand' => esc_html__('Brand Icons', 'topseo'),
            'medical' => esc_html__('Medical Icons', 'topseo'),
        ),
        'icons' => array(
            // Ion Icons
            'ion-ionic' => array('group' => 'ion-icon'),
            'ion-alert' => array('group' => 'ion-icon'),
            'ion-alert-circled' => array('group' => 'ion-icon'),
            'ion-android-add' => array('group' => 'ion-icon'),
            'ion-android-add-circle' => array('group' => 'ion-icon'),
            'ion-android-alarm-clock' => array('group' => 'ion-icon'),
            'ion-android-alert' => array('group' => 'ion-icon'),
            'ion-android-apps' => array('group' => 'ion-icon'),
            'ion-android-archive' => array('group' => 'ion-icon'),
            'ion-android-arrow-back' => array('group' => 'ion-icon'),
            'ion-android-arrow-down' => array('group' => 'ion-icon'),
            'ion-android-arrow-dropdown' => array('group' => 'ion-icon'),
            'ion-android-arrow-dropdown-circle' => array('group' => 'ion-icon'),
            'ion-android-arrow-dropleft' => array('group' => 'ion-icon'),
            'ion-android-arrow-dropleft-circle' => array('group' => 'ion-icon'),
            'ion-android-arrow-dropright' => array('group' => 'ion-icon'),
            'ion-android-arrow-dropright-circle' => array('group' => 'ion-icon'),
            'ion-android-arrow-dropup' => array('group' => 'ion-icon'),
            'ion-android-arrow-dropup-circle' => array('group' => 'ion-icon'),
            'ion-android-arrow-forward' => array('group' => 'ion-icon'),
            'ion-android-arrow-up' => array('group' => 'ion-icon'),
            'ion-android-attach' => array('group' => 'ion-icon'),
            'ion-android-bar' => array('group' => 'ion-icon'),
            'ion-android-bicycle' => array('group' => 'ion-icon'),
            'ion-android-boat' => array('group' => 'ion-icon'),
            'ion-android-bookmark' => array('group' => 'ion-icon'),
            'ion-android-bulb' => array('group' => 'ion-icon'),
            'ion-android-bus' => array('group' => 'ion-icon'),
            'ion-android-calendar' => array('group' => 'ion-icon'),
            'ion-android-call' => array('group' => 'ion-icon'),
            'ion-android-camera' => array('group' => 'ion-icon'),
            'ion-android-cancel' => array('group' => 'ion-icon'),
            'ion-android-car' => array('group' => 'ion-icon'),
            'ion-android-cart' => array('group' => 'ion-icon'),
            'ion-android-chat' => array('group' => 'ion-icon'),
            'ion-android-checkbox' => array('group' => 'ion-icon'),
            'ion-android-checkbox-blank' => array('group' => 'ion-icon'),
            'ion-android-checkbox-outline' => array('group' => 'ion-icon'),
            'ion-android-checkbox-outline-blank' => array('group' => 'ion-icon'),
            'ion-android-checkmark-circle' => array('group' => 'ion-icon'),
            'ion-android-clipboard' => array('group' => 'ion-icon'),
            'ion-android-close' => array('group' => 'ion-icon'),
            'ion-android-cloud' => array('group' => 'ion-icon'),
            'ion-android-cloud-circle' => array('group' => 'ion-icon'),
            'ion-android-cloud-done' => array('group' => 'ion-icon'),
            'ion-android-cloud-outline' => array('group' => 'ion-icon'),
            'ion-android-color-palette' => array('group' => 'ion-icon'),
            'ion-android-compass' => array('group' => 'ion-icon'),
            'ion-android-contact' => array('group' => 'ion-icon'),
            'ion-android-contacts' => array('group' => 'ion-icon'),
            'ion-android-contract' => array('group' => 'ion-icon'),
            'ion-android-create' => array('group' => 'ion-icon'),
            'ion-android-delete' => array('group' => 'ion-icon'),
            'ion-android-desktop' => array('group' => 'ion-icon'),
            'ion-android-document' => array('group' => 'ion-icon'),
            'ion-android-done' => array('group' => 'ion-icon'),
            'ion-android-done-all' => array('group' => 'ion-icon'),
            'ion-android-download' => array('group' => 'ion-icon'),
            'ion-android-drafts' => array('group' => 'ion-icon'),
            'ion-android-exit' => array('group' => 'ion-icon'),
            'ion-android-expand' => array('group' => 'ion-icon'),
            'ion-android-favorite' => array('group' => 'ion-icon'),
            'ion-android-favorite-outline' => array('group' => 'ion-icon'),
            'ion-android-film' => array('group' => 'ion-icon'),
            'ion-android-folder' => array('group' => 'ion-icon'),
            'ion-android-folder-open' => array('group' => 'ion-icon'),
            'ion-android-funnel' => array('group' => 'ion-icon'),
            'ion-android-globe' => array('group' => 'ion-icon'),
            'ion-android-hand' => array('group' => 'ion-icon'),
            'ion-android-hangout' => array('group' => 'ion-icon'),
            'ion-android-happy' => array('group' => 'ion-icon'),
            'ion-android-home' => array('group' => 'ion-icon'),
            'ion-android-image' => array('group' => 'ion-icon'),
            'ion-android-laptop' => array('group' => 'ion-icon'),
            'ion-android-list' => array('group' => 'ion-icon'),
            'ion-android-locate' => array('group' => 'ion-icon'),
            'ion-android-lock' => array('group' => 'ion-icon'),
            'ion-android-mail' => array('group' => 'ion-icon'),
            'ion-android-map' => array('group' => 'ion-icon'),
            'ion-android-menu' => array('group' => 'ion-icon'),
            'ion-android-microphone' => array('group' => 'ion-icon'),
            'ion-android-microphone-off' => array('group' => 'ion-icon'),
            'ion-android-more-horizontal' => array('group' => 'ion-icon'),
            'ion-android-more-vertical' => array('group' => 'ion-icon'),
            'ion-android-navigate' => array('group' => 'ion-icon'),
            'ion-android-notifications' => array('group' => 'ion-icon'),
            'ion-android-notifications-none' => array('group' => 'ion-icon'),
            'ion-android-notifications-off' => array('group' => 'ion-icon'),
            'ion-android-open' => array('group' => 'ion-icon'),
            'ion-android-options' => array('group' => 'ion-icon'),
            'ion-android-people' => array('group' => 'ion-icon'),
            'ion-android-person' => array('group' => 'ion-icon'),
            'ion-android-person-add' => array('group' => 'ion-icon'),
            'ion-android-phone-landscape' => array('group' => 'ion-icon'),
            'ion-android-phone-portrait' => array('group' => 'ion-icon'),
            'ion-android-pin' => array('group' => 'ion-icon'),
            'ion-android-plane' => array('group' => 'ion-icon'),
            'ion-android-playstore' => array('group' => 'ion-icon'),
            'ion-android-print' => array('group' => 'ion-icon'),
            'ion-android-radio-button-off' => array('group' => 'ion-icon'),
            'ion-android-radio-button-on' => array('group' => 'ion-icon'),
            'ion-android-refresh' => array('group' => 'ion-icon'),
            'ion-android-remove' => array('group' => 'ion-icon'),
            'ion-android-remove-circle' => array('group' => 'ion-icon'),
            'ion-android-restaurant' => array('group' => 'ion-icon'),
            'ion-android-sad' => array('group' => 'ion-icon'),
            'ion-android-search' => array('group' => 'ion-icon'),
            'ion-android-send' => array('group' => 'ion-icon'),
            'ion-android-settings' => array('group' => 'ion-icon'),
            'ion-android-share' => array('group' => 'ion-icon'),
            'ion-android-share-alt' => array('group' => 'ion-icon'),
            'ion-android-star' => array('group' => 'ion-icon'),
            'ion-android-star-half' => array('group' => 'ion-icon'),
            'ion-android-star-outline' => array('group' => 'ion-icon'),
            'ion-android-stopwatch' => array('group' => 'ion-icon'),
            'ion-android-subway' => array('group' => 'ion-icon'),
            'ion-android-sunny' => array('group' => 'ion-icon'),
            'ion-android-sync' => array('group' => 'ion-icon'),
            'ion-android-textsms' => array('group' => 'ion-icon'),
            'ion-android-time' => array('group' => 'ion-icon'),
            'ion-android-train' => array('group' => 'ion-icon'),
            'ion-android-unlock' => array('group' => 'ion-icon'),
            'ion-android-upload' => array('group' => 'ion-icon'),
            'ion-android-volume-down' => array('group' => 'ion-icon'),
            'ion-android-volume-mute' => array('group' => 'ion-icon'),
            'ion-android-volume-off' => array('group' => 'ion-icon'),
            'ion-android-volume-up' => array('group' => 'ion-icon'),
            'ion-android-walk' => array('group' => 'ion-icon'),
            'ion-android-warning' => array('group' => 'ion-icon'),
            'ion-android-watch' => array('group' => 'ion-icon'),
            'ion-android-wifi' => array('group' => 'ion-icon'),
            'ion-aperture' => array('group' => 'ion-icon'),
            'ion-archive' => array('group' => 'ion-icon'),
            'ion-arrow-down-a' => array('group' => 'ion-icon'),
            'ion-arrow-down-b' => array('group' => 'ion-icon'),
            'ion-arrow-down-c' => array('group' => 'ion-icon'),
            'ion-arrow-expand' => array('group' => 'ion-icon'),
            'ion-arrow-graph-down-left' => array('group' => 'ion-icon'),
            'ion-arrow-graph-down-right' => array('group' => 'ion-icon'),
            'ion-arrow-graph-up-left' => array('group' => 'ion-icon'),
            'ion-arrow-graph-up-right' => array('group' => 'ion-icon'),
            'ion-arrow-left-a' => array('group' => 'ion-icon'),
            'ion-arrow-left-b' => array('group' => 'ion-icon'),
            'ion-arrow-left-c' => array('group' => 'ion-icon'),
            'ion-arrow-move' => array('group' => 'ion-icon'),
            'ion-arrow-resize' => array('group' => 'ion-icon'),
            'ion-arrow-return-left' => array('group' => 'ion-icon'),
            'ion-arrow-return-right' => array('group' => 'ion-icon'),
            'ion-arrow-right-a' => array('group' => 'ion-icon'),
            'ion-arrow-right-b' => array('group' => 'ion-icon'),
            'ion-arrow-right-c' => array('group' => 'ion-icon'),
            'ion-arrow-shrink' => array('group' => 'ion-icon'),
            'ion-arrow-swap' => array('group' => 'ion-icon'),
            'ion-arrow-up-a' => array('group' => 'ion-icon'),
            'ion-arrow-up-b' => array('group' => 'ion-icon'),
            'ion-arrow-up-c' => array('group' => 'ion-icon'),
            'ion-asterisk' => array('group' => 'ion-icon'),
            'ion-at' => array('group' => 'ion-icon'),
            'ion-backspace' => array('group' => 'ion-icon'),
            'ion-backspace-outline' => array('group' => 'ion-icon'),
            'ion-bag' => array('group' => 'ion-icon'),
            'ion-battery-charging' => array('group' => 'ion-icon'),
            'ion-battery-empty' => array('group' => 'ion-icon'),
            'ion-battery-full' => array('group' => 'ion-icon'),
            'ion-battery-half' => array('group' => 'ion-icon'),
            'ion-battery-low' => array('group' => 'ion-icon'),
            'ion-beaker' => array('group' => 'ion-icon'),
            'ion-beer' => array('group' => 'ion-icon'),
            'ion-bluetooth' => array('group' => 'ion-icon'),
            'ion-bonfire' => array('group' => 'ion-icon'),
            'ion-bookmark' => array('group' => 'ion-icon'),
            'ion-bowtie' => array('group' => 'ion-icon'),
            'ion-briefcase' => array('group' => 'ion-icon'),
            'ion-bug' => array('group' => 'ion-icon'),
            'ion-calculator' => array('group' => 'ion-icon'),
            'ion-calendar' => array('group' => 'ion-icon'),
            'ion-camera' => array('group' => 'ion-icon'),
            'ion-card' => array('group' => 'ion-icon'),
            'ion-cash' => array('group' => 'ion-icon'),
            'ion-chatbox' => array('group' => 'ion-icon'),
            'ion-chatbox-working' => array('group' => 'ion-icon'),
            'ion-chatboxes' => array('group' => 'ion-icon'),
            'ion-chatbubble' => array('group' => 'ion-icon'),
            'ion-chatbubble-working' => array('group' => 'ion-icon'),
            'ion-chatbubbles' => array('group' => 'ion-icon'),
            'ion-checkmark' => array('group' => 'ion-icon'),
            'ion-checkmark-circled' => array('group' => 'ion-icon'),
            'ion-checkmark-round' => array('group' => 'ion-icon'),
            'ion-chevron-down' => array('group' => 'ion-icon'),
            'ion-chevron-left' => array('group' => 'ion-icon'),
            'ion-chevron-right' => array('group' => 'ion-icon'),
            'ion-chevron-up' => array('group' => 'ion-icon'),
            'ion-clipboard' => array('group' => 'ion-icon'),
            'ion-clock' => array('group' => 'ion-icon'),
            'ion-close' => array('group' => 'ion-icon'),
            'ion-close-circled' => array('group' => 'ion-icon'),
            'ion-close-round' => array('group' => 'ion-icon'),
            'ion-closed-captioning' => array('group' => 'ion-icon'),
            'ion-cloud' => array('group' => 'ion-icon'),
            'ion-code' => array('group' => 'ion-icon'),
            'ion-code-download' => array('group' => 'ion-icon'),
            'ion-code-working' => array('group' => 'ion-icon'),
            'ion-coffee' => array('group' => 'ion-icon'),
            'ion-compass' => array('group' => 'ion-icon'),
            'ion-compose' => array('group' => 'ion-icon'),
            'ion-connection-bars' => array('group' => 'ion-icon'),
            'ion-contrast' => array('group' => 'ion-icon'),
            'ion-crop' => array('group' => 'ion-icon'),
            'ion-cube' => array('group' => 'ion-icon'),
            'ion-disc' => array('group' => 'ion-icon'),
            'ion-document' => array('group' => 'ion-icon'),
            'ion-document-text' => array('group' => 'ion-icon'),
            'ion-drag' => array('group' => 'ion-icon'),
            'ion-earth' => array('group' => 'ion-icon'),
            'ion-easel' => array('group' => 'ion-icon'),
            'ion-edit' => array('group' => 'ion-icon'),
            'ion-egg' => array('group' => 'ion-icon'),
            'ion-eject' => array('group' => 'ion-icon'),
            'ion-email' => array('group' => 'ion-icon'),
            'ion-email-unread' => array('group' => 'ion-icon'),
            'ion-erlenmeyer-flask' => array('group' => 'ion-icon'),
            'ion-erlenmeyer-flask-bubbles' => array('group' => 'ion-icon'),
            'ion-eye' => array('group' => 'ion-icon'),
            'ion-eye-disabled' => array('group' => 'ion-icon'),
            'ion-female' => array('group' => 'ion-icon'),
            'ion-filing' => array('group' => 'ion-icon'),
            'ion-film-marker' => array('group' => 'ion-icon'),
            'ion-fireball' => array('group' => 'ion-icon'),
            'ion-flag' => array('group' => 'ion-icon'),
            'ion-flame' => array('group' => 'ion-icon'),
            'ion-flash' => array('group' => 'ion-icon'),
            'ion-flash-off' => array('group' => 'ion-icon'),
            'ion-folder' => array('group' => 'ion-icon'),
            'ion-fork' => array('group' => 'ion-icon'),
            'ion-fork-repo' => array('group' => 'ion-icon'),
            'ion-forward' => array('group' => 'ion-icon'),
            'ion-funnel' => array('group' => 'ion-icon'),
            'ion-gear-a' => array('group' => 'ion-icon'),
            'ion-gear-b' => array('group' => 'ion-icon'),
            'ion-grid' => array('group' => 'ion-icon'),
            'ion-hammer' => array('group' => 'ion-icon'),
            'ion-happy' => array('group' => 'ion-icon'),
            'ion-happy-outline' => array('group' => 'ion-icon'),
            'ion-headphone' => array('group' => 'ion-icon'),
            'ion-heart' => array('group' => 'ion-icon'),
            'ion-heart-broken' => array('group' => 'ion-icon'),
            'ion-help' => array('group' => 'ion-icon'),
            'ion-help-buoy' => array('group' => 'ion-icon'),
            'ion-help-circled' => array('group' => 'ion-icon'),
            'ion-home' => array('group' => 'ion-icon'),
            'ion-icecream' => array('group' => 'ion-icon'),
            'ion-image' => array('group' => 'ion-icon'),
            'ion-images' => array('group' => 'ion-icon'),
            'ion-information' => array('group' => 'ion-icon'),
            'ion-information-circled' => array('group' => 'ion-icon'),
            'ion-ionic' => array('group' => 'ion-icon'),
            'ion-ios-alarm' => array('group' => 'ion-icon'),
            'ion-ios-alarm-outline' => array('group' => 'ion-icon'),
            'ion-ios-albums' => array('group' => 'ion-icon'),
            'ion-ios-albums-outline' => array('group' => 'ion-icon'),
            'ion-ios-americanfootball' => array('group' => 'ion-icon'),
            'ion-ios-americanfootball-outline' => array('group' => 'ion-icon'),
            'ion-ios-analytics' => array('group' => 'ion-icon'),
            'ion-ios-analytics-outline' => array('group' => 'ion-icon'),
            'ion-ios-arrow-back' => array('group' => 'ion-icon'),
            'ion-ios-arrow-down' => array('group' => 'ion-icon'),
            'ion-ios-arrow-forward' => array('group' => 'ion-icon'),
            'ion-ios-arrow-left' => array('group' => 'ion-icon'),
            'ion-ios-arrow-right' => array('group' => 'ion-icon'),
            'ion-ios-arrow-thin-down' => array('group' => 'ion-icon'),
            'ion-ios-arrow-thin-left' => array('group' => 'ion-icon'),
            'ion-ios-arrow-thin-right' => array('group' => 'ion-icon'),
            'ion-ios-arrow-thin-up' => array('group' => 'ion-icon'),
            'ion-ios-arrow-up' => array('group' => 'ion-icon'),
            'ion-ios-at' => array('group' => 'ion-icon'),
            'ion-ios-at-outline' => array('group' => 'ion-icon'),
            'ion-ios-barcode' => array('group' => 'ion-icon'),
            'ion-ios-barcode-outline' => array('group' => 'ion-icon'),
            'ion-ios-baseball' => array('group' => 'ion-icon'),
            'ion-ios-baseball-outline' => array('group' => 'ion-icon'),
            'ion-ios-basketball' => array('group' => 'ion-icon'),
            'ion-ios-basketball-outline' => array('group' => 'ion-icon'),
            'ion-ios-bell' => array('group' => 'ion-icon'),
            'ion-ios-bell-outline' => array('group' => 'ion-icon'),
            'ion-ios-body' => array('group' => 'ion-icon'),
            'ion-ios-body-outline' => array('group' => 'ion-icon'),
            'ion-ios-bolt' => array('group' => 'ion-icon'),
            'ion-ios-bolt-outline' => array('group' => 'ion-icon'),
            'ion-ios-book' => array('group' => 'ion-icon'),
            'ion-ios-book-outline' => array('group' => 'ion-icon'),
            'ion-ios-bookmarks' => array('group' => 'ion-icon'),
            'ion-ios-bookmarks-outline' => array('group' => 'ion-icon'),
            'ion-ios-box' => array('group' => 'ion-icon'),
            'ion-ios-box-outline' => array('group' => 'ion-icon'),
            'ion-ios-briefcase' => array('group' => 'ion-icon'),
            'ion-ios-briefcase-outline' => array('group' => 'ion-icon'),
            'ion-ios-browsers' => array('group' => 'ion-icon'),
            'ion-ios-browsers-outline' => array('group' => 'ion-icon'),
            'ion-ios-calculator' => array('group' => 'ion-icon'),
            'ion-ios-calculator-outline' => array('group' => 'ion-icon'),
            'ion-ios-calendar' => array('group' => 'ion-icon'),
            'ion-ios-calendar-outline' => array('group' => 'ion-icon'),
            'ion-ios-camera' => array('group' => 'ion-icon'),
            'ion-ios-camera-outline' => array('group' => 'ion-icon'),
            'ion-ios-cart' => array('group' => 'ion-icon'),
            'ion-ios-cart-outline' => array('group' => 'ion-icon'),
            'ion-ios-chatboxes' => array('group' => 'ion-icon'),
            'ion-ios-chatboxes-outline' => array('group' => 'ion-icon'),
            'ion-ios-chatbubble' => array('group' => 'ion-icon'),
            'ion-ios-chatbubble-outline' => array('group' => 'ion-icon'),
            'ion-ios-checkmark' => array('group' => 'ion-icon'),
            'ion-ios-checkmark-empty' => array('group' => 'ion-icon'),
            'ion-ios-checkmark-outline' => array('group' => 'ion-icon'),
            'ion-ios-circle-filled' => array('group' => 'ion-icon'),
            'ion-ios-circle-outline' => array('group' => 'ion-icon'),
            'ion-ios-clock' => array('group' => 'ion-icon'),
            'ion-ios-clock-outline' => array('group' => 'ion-icon'),
            'ion-ios-close' => array('group' => 'ion-icon'),
            'ion-ios-close-empty' => array('group' => 'ion-icon'),
            'ion-ios-close-outline' => array('group' => 'ion-icon'),
            'ion-ios-cloud' => array('group' => 'ion-icon'),
            'ion-ios-cloud-download' => array('group' => 'ion-icon'),
            'ion-ios-cloud-download-outline' => array('group' => 'ion-icon'),
            'ion-ios-cloud-outline' => array('group' => 'ion-icon'),
            'ion-ios-cloud-upload' => array('group' => 'ion-icon'),
            'ion-ios-cloud-upload-outline' => array('group' => 'ion-icon'),
            'ion-ios-cloudy' => array('group' => 'ion-icon'),
            'ion-ios-cloudy-night' => array('group' => 'ion-icon'),
            'ion-ios-cloudy-night-outline' => array('group' => 'ion-icon'),
            'ion-ios-cloudy-outline' => array('group' => 'ion-icon'),
            'ion-ios-cog' => array('group' => 'ion-icon'),
            'ion-ios-cog-outline' => array('group' => 'ion-icon'),
            'ion-ios-color-filter' => array('group' => 'ion-icon'),
            'ion-ios-color-filter-outline' => array('group' => 'ion-icon'),
            'ion-ios-color-wand' => array('group' => 'ion-icon'),
            'ion-ios-color-wand-outline' => array('group' => 'ion-icon'),
            'ion-ios-compose' => array('group' => 'ion-icon'),
            'ion-ios-compose-outline' => array('group' => 'ion-icon'),
            'ion-ios-contact' => array('group' => 'ion-icon'),
            'ion-ios-contact-outline' => array('group' => 'ion-icon'),
            'ion-ios-copy' => array('group' => 'ion-icon'),
            'ion-ios-copy-outline' => array('group' => 'ion-icon'),
            'ion-ios-crop' => array('group' => 'ion-icon'),
            'ion-ios-crop-strong' => array('group' => 'ion-icon'),
            'ion-ios-download' => array('group' => 'ion-icon'),
            'ion-ios-download-outline' => array('group' => 'ion-icon'),
            'ion-ios-drag' => array('group' => 'ion-icon'),
            'ion-ios-email' => array('group' => 'ion-icon'),
            'ion-ios-email-outline' => array('group' => 'ion-icon'),
            'ion-ios-eye' => array('group' => 'ion-icon'),
            'ion-ios-eye-outline' => array('group' => 'ion-icon'),
            'ion-ios-fastforward' => array('group' => 'ion-icon'),
            'ion-ios-fastforward-outline' => array('group' => 'ion-icon'),
            'ion-ios-filing' => array('group' => 'ion-icon'),
            'ion-ios-filing-outline' => array('group' => 'ion-icon'),
            'ion-ios-film' => array('group' => 'ion-icon'),
            'ion-ios-film-outline' => array('group' => 'ion-icon'),
            'ion-ios-flag' => array('group' => 'ion-icon'),
            'ion-ios-flag-outline' => array('group' => 'ion-icon'),
            'ion-ios-flame' => array('group' => 'ion-icon'),
            'ion-ios-flame-outline' => array('group' => 'ion-icon'),
            'ion-ios-flask' => array('group' => 'ion-icon'),
            'ion-ios-flask-outline' => array('group' => 'ion-icon'),
            'ion-ios-flower' => array('group' => 'ion-icon'),
            'ion-ios-flower-outline' => array('group' => 'ion-icon'),
            'ion-ios-folder' => array('group' => 'ion-icon'),
            'ion-ios-folder-outline' => array('group' => 'ion-icon'),
            'ion-ios-football' => array('group' => 'ion-icon'),
            'ion-ios-football-outline' => array('group' => 'ion-icon'),
            'ion-ios-game-controller-a' => array('group' => 'ion-icon'),
            'ion-ios-game-controller-a-outline' => array('group' => 'ion-icon'),
            'ion-ios-game-controller-b' => array('group' => 'ion-icon'),
            'ion-ios-game-controller-b-outline' => array('group' => 'ion-icon'),
            'ion-ios-gear' => array('group' => 'ion-icon'),
            'ion-ios-gear-outline' => array('group' => 'ion-icon'),
            'ion-ios-glasses' => array('group' => 'ion-icon'),
            'ion-ios-glasses-outline' => array('group' => 'ion-icon'),
            'ion-ios-grid-view' => array('group' => 'ion-icon'),
            'ion-ios-grid-view-outline' => array('group' => 'ion-icon'),
            'ion-ios-heart' => array('group' => 'ion-icon'),
            'ion-ios-heart-outline' => array('group' => 'ion-icon'),
            'ion-ios-help' => array('group' => 'ion-icon'),
            'ion-ios-help-empty' => array('group' => 'ion-icon'),
            'ion-ios-help-outline' => array('group' => 'ion-icon'),
            'ion-ios-home' => array('group' => 'ion-icon'),
            'ion-ios-home-outline' => array('group' => 'ion-icon'),
            'ion-ios-infinite' => array('group' => 'ion-icon'),
            'ion-ios-infinite-outline' => array('group' => 'ion-icon'),
            'ion-ios-information' => array('group' => 'ion-icon'),
            'ion-ios-information-empty' => array('group' => 'ion-icon'),
            'ion-ios-information-outline' => array('group' => 'ion-icon'),
            'ion-ios-ionic-outline' => array('group' => 'ion-icon'),
            'ion-ios-keypad' => array('group' => 'ion-icon'),
            'ion-ios-keypad-outline' => array('group' => 'ion-icon'),
            'ion-ios-lightbulb' => array('group' => 'ion-icon'),
            'ion-ios-lightbulb-outline' => array('group' => 'ion-icon'),
            'ion-ios-list' => array('group' => 'ion-icon'),
            'ion-ios-list-outline' => array('group' => 'ion-icon'),
            'ion-ios-location' => array('group' => 'ion-icon'),
            'ion-ios-location-outline' => array('group' => 'ion-icon'),
            'ion-ios-locked' => array('group' => 'ion-icon'),
            'ion-ios-locked-outline' => array('group' => 'ion-icon'),
            'ion-ios-loop' => array('group' => 'ion-icon'),
            'ion-ios-loop-strong' => array('group' => 'ion-icon'),
            'ion-ios-medical' => array('group' => 'ion-icon'),
            'ion-ios-medical-outline' => array('group' => 'ion-icon'),
            'ion-ios-medkit' => array('group' => 'ion-icon'),
            'ion-ios-medkit-outline' => array('group' => 'ion-icon'),
            'ion-ios-mic' => array('group' => 'ion-icon'),
            'ion-ios-mic-off' => array('group' => 'ion-icon'),
            'ion-ios-mic-outline' => array('group' => 'ion-icon'),
            'ion-ios-minus' => array('group' => 'ion-icon'),
            'ion-ios-minus-empty' => array('group' => 'ion-icon'),
            'ion-ios-minus-outline' => array('group' => 'ion-icon'),
            'ion-ios-monitor' => array('group' => 'ion-icon'),
            'ion-ios-monitor-outline' => array('group' => 'ion-icon'),
            'ion-ios-moon' => array('group' => 'ion-icon'),
            'ion-ios-moon-outline' => array('group' => 'ion-icon'),
            'ion-ios-more' => array('group' => 'ion-icon'),
            'ion-ios-more-outline' => array('group' => 'ion-icon'),
            'ion-ios-musical-note' => array('group' => 'ion-icon'),
            'ion-ios-musical-notes' => array('group' => 'ion-icon'),
            'ion-ios-navigate' => array('group' => 'ion-icon'),
            'ion-ios-navigate-outline' => array('group' => 'ion-icon'),
            'ion-ios-nutrition' => array('group' => 'ion-icon'),
            'ion-ios-nutrition-outline' => array('group' => 'ion-icon'),
            'ion-ios-paper' => array('group' => 'ion-icon'),
            'ion-ios-paper-outline' => array('group' => 'ion-icon'),
            'ion-ios-paperplane' => array('group' => 'ion-icon'),
            'ion-ios-paperplane-outline' => array('group' => 'ion-icon'),
            'ion-ios-partlysunny' => array('group' => 'ion-icon'),
            'ion-ios-partlysunny-outline' => array('group' => 'ion-icon'),
            'ion-ios-pause' => array('group' => 'ion-icon'),
            'ion-ios-pause-outline' => array('group' => 'ion-icon'),
            'ion-ios-paw' => array('group' => 'ion-icon'),
            'ion-ios-paw-outline' => array('group' => 'ion-icon'),
            'ion-ios-people' => array('group' => 'ion-icon'),
            'ion-ios-people-outline' => array('group' => 'ion-icon'),
            'ion-ios-person' => array('group' => 'ion-icon'),
            'ion-ios-person-outline' => array('group' => 'ion-icon'),
            'ion-ios-personadd' => array('group' => 'ion-icon'),
            'ion-ios-personadd-outline' => array('group' => 'ion-icon'),
            'ion-ios-photos' => array('group' => 'ion-icon'),
            'ion-ios-photos-outline' => array('group' => 'ion-icon'),
            'ion-ios-pie' => array('group' => 'ion-icon'),
            'ion-ios-pie-outline' => array('group' => 'ion-icon'),
            'ion-ios-pint' => array('group' => 'ion-icon'),
            'ion-ios-pint-outline' => array('group' => 'ion-icon'),
            'ion-ios-play' => array('group' => 'ion-icon'),
            'ion-ios-play-outline' => array('group' => 'ion-icon'),
            'ion-ios-plus' => array('group' => 'ion-icon'),
            'ion-ios-plus-empty' => array('group' => 'ion-icon'),
            'ion-ios-plus-outline' => array('group' => 'ion-icon'),
            'ion-ios-pricetag' => array('group' => 'ion-icon'),
            'ion-ios-pricetag-outline' => array('group' => 'ion-icon'),
            'ion-ios-pricetags' => array('group' => 'ion-icon'),
            'ion-ios-pricetags-outline' => array('group' => 'ion-icon'),
            'ion-ios-printer' => array('group' => 'ion-icon'),
            'ion-ios-printer-outline' => array('group' => 'ion-icon'),
            'ion-ios-pulse' => array('group' => 'ion-icon'),
            'ion-ios-pulse-strong' => array('group' => 'ion-icon'),
            'ion-ios-rainy' => array('group' => 'ion-icon'),
            'ion-ios-rainy-outline' => array('group' => 'ion-icon'),
            'ion-ios-recording' => array('group' => 'ion-icon'),
            'ion-ios-recording-outline' => array('group' => 'ion-icon'),
            'ion-ios-redo' => array('group' => 'ion-icon'),
            'ion-ios-redo-outline' => array('group' => 'ion-icon'),
            'ion-ios-refresh' => array('group' => 'ion-icon'),
            'ion-ios-refresh-empty' => array('group' => 'ion-icon'),
            'ion-ios-refresh-outline' => array('group' => 'ion-icon'),
            'ion-ios-reload' => array('group' => 'ion-icon'),
            'ion-ios-reverse-camera' => array('group' => 'ion-icon'),
            'ion-ios-reverse-camera-outline' => array('group' => 'ion-icon'),
            'ion-ios-rewind' => array('group' => 'ion-icon'),
            'ion-ios-rewind-outline' => array('group' => 'ion-icon'),
            'ion-ios-rose' => array('group' => 'ion-icon'),
            'ion-ios-rose-outline' => array('group' => 'ion-icon'),
            'ion-ios-search' => array('group' => 'ion-icon'),
            'ion-ios-search-strong' => array('group' => 'ion-icon'),
            'ion-ios-settings' => array('group' => 'ion-icon'),
            'ion-ios-settings-strong' => array('group' => 'ion-icon'),
            'ion-ios-shuffle' => array('group' => 'ion-icon'),
            'ion-ios-shuffle-strong' => array('group' => 'ion-icon'),
            'ion-ios-skipbackward' => array('group' => 'ion-icon'),
            'ion-ios-skipbackward-outline' => array('group' => 'ion-icon'),
            'ion-ios-skipforward' => array('group' => 'ion-icon'),
            'ion-ios-skipforward-outline' => array('group' => 'ion-icon'),
            'ion-ios-snowy' => array('group' => 'ion-icon'),
            'ion-ios-speedometer' => array('group' => 'ion-icon'),
            'ion-ios-speedometer-outline' => array('group' => 'ion-icon'),
            'ion-ios-star' => array('group' => 'ion-icon'),
            'ion-ios-star-half' => array('group' => 'ion-icon'),
            'ion-ios-star-outline' => array('group' => 'ion-icon'),
            'ion-ios-stopwatch' => array('group' => 'ion-icon'),
            'ion-ios-stopwatch-outline' => array('group' => 'ion-icon'),
            'ion-ios-sunny' => array('group' => 'ion-icon'),
            'ion-ios-sunny-outline' => array('group' => 'ion-icon'),
            'ion-ios-telephone' => array('group' => 'ion-icon'),
            'ion-ios-telephone-outline' => array('group' => 'ion-icon'),
            'ion-ios-tennisball' => array('group' => 'ion-icon'),
            'ion-ios-tennisball-outline' => array('group' => 'ion-icon'),
            'ion-ios-thunderstorm' => array('group' => 'ion-icon'),
            'ion-ios-thunderstorm-outline' => array('group' => 'ion-icon'),
            'ion-ios-time' => array('group' => 'ion-icon'),
            'ion-ios-time-outline' => array('group' => 'ion-icon'),
            'ion-ios-timer' => array('group' => 'ion-icon'),
            'ion-ios-timer-outline' => array('group' => 'ion-icon'),
            'ion-ios-toggle' => array('group' => 'ion-icon'),
            'ion-ios-toggle-outline' => array('group' => 'ion-icon'),
            'ion-ios-trash' => array('group' => 'ion-icon'),
            'ion-ios-trash-outline' => array('group' => 'ion-icon'),
            'ion-ios-undo' => array('group' => 'ion-icon'),
            'ion-ios-undo-outline' => array('group' => 'ion-icon'),
            'ion-ios-unlocked' => array('group' => 'ion-icon'),
            'ion-ios-unlocked-outline' => array('group' => 'ion-icon'),
            'ion-ios-upload' => array('group' => 'ion-icon'),
            'ion-ios-upload-outline' => array('group' => 'ion-icon'),
            'ion-ios-videocam' => array('group' => 'ion-icon'),
            'ion-ios-videocam-outline' => array('group' => 'ion-icon'),
            'ion-ios-volume-high' => array('group' => 'ion-icon'),
            'ion-ios-volume-low' => array('group' => 'ion-icon'),
            'ion-ios-wineglass' => array('group' => 'ion-icon'),
            'ion-ios-wineglass-outline' => array('group' => 'ion-icon'),
            'ion-ios-world' => array('group' => 'ion-icon'),
            'ion-ios-world-outline' => array('group' => 'ion-icon'),
            'ion-ipad' => array('group' => 'ion-icon'),
            'ion-iphone' => array('group' => 'ion-icon'),
            'ion-ipod' => array('group' => 'ion-icon'),
            'ion-jet' => array('group' => 'ion-icon'),
            'ion-key' => array('group' => 'ion-icon'),
            'ion-knife' => array('group' => 'ion-icon'),
            'ion-laptop' => array('group' => 'ion-icon'),
            'ion-leaf' => array('group' => 'ion-icon'),
            'ion-levels' => array('group' => 'ion-icon'),
            'ion-lightbulb' => array('group' => 'ion-icon'),
            'ion-link' => array('group' => 'ion-icon'),
            'ion-load-a' => array('group' => 'ion-icon'),
            'ion-load-b' => array('group' => 'ion-icon'),
            'ion-load-c' => array('group' => 'ion-icon'),
            'ion-load-d' => array('group' => 'ion-icon'),
            'ion-location' => array('group' => 'ion-icon'),
            'ion-lock-combination' => array('group' => 'ion-icon'),
            'ion-locked' => array('group' => 'ion-icon'),
            'ion-log-in' => array('group' => 'ion-icon'),
            'ion-log-out' => array('group' => 'ion-icon'),
            'ion-loop' => array('group' => 'ion-icon'),
            'ion-magnet' => array('group' => 'ion-icon'),
            'ion-male' => array('group' => 'ion-icon'),
            'ion-man' => array('group' => 'ion-icon'),
            'ion-map' => array('group' => 'ion-icon'),
            'ion-medkit' => array('group' => 'ion-icon'),
            'ion-merge' => array('group' => 'ion-icon'),
            'ion-mic-a' => array('group' => 'ion-icon'),
            'ion-mic-b' => array('group' => 'ion-icon'),
            'ion-mic-c' => array('group' => 'ion-icon'),
            'ion-minus' => array('group' => 'ion-icon'),
            'ion-minus-circled' => array('group' => 'ion-icon'),
            'ion-minus-round' => array('group' => 'ion-icon'),
            'ion-model-s' => array('group' => 'ion-icon'),
            'ion-monitor' => array('group' => 'ion-icon'),
            'ion-more' => array('group' => 'ion-icon'),
            'ion-mouse' => array('group' => 'ion-icon'),
            'ion-music-note' => array('group' => 'ion-icon'),
            'ion-navicon' => array('group' => 'ion-icon'),
            'ion-navicon-round' => array('group' => 'ion-icon'),
            'ion-navigate' => array('group' => 'ion-icon'),
            'ion-network' => array('group' => 'ion-icon'),
            'ion-no-smoking' => array('group' => 'ion-icon'),
            'ion-nuclear' => array('group' => 'ion-icon'),
            'ion-outlet' => array('group' => 'ion-icon'),
            'ion-paintbrush' => array('group' => 'ion-icon'),
            'ion-paintbucket' => array('group' => 'ion-icon'),
            'ion-paper-airplane' => array('group' => 'ion-icon'),
            'ion-paperclip' => array('group' => 'ion-icon'),
            'ion-pause' => array('group' => 'ion-icon'),
            'ion-person' => array('group' => 'ion-icon'),
            'ion-person-add' => array('group' => 'ion-icon'),
            'ion-person-stalker' => array('group' => 'ion-icon'),
            'ion-pie-graph' => array('group' => 'ion-icon'),
            'ion-pin' => array('group' => 'ion-icon'),
            'ion-pinpoint' => array('group' => 'ion-icon'),
            'ion-pizza' => array('group' => 'ion-icon'),
            'ion-plane' => array('group' => 'ion-icon'),
            'ion-planet' => array('group' => 'ion-icon'),
            'ion-play' => array('group' => 'ion-icon'),
            'ion-playstation' => array('group' => 'ion-icon'),
            'ion-plus' => array('group' => 'ion-icon'),
            'ion-plus-circled' => array('group' => 'ion-icon'),
            'ion-plus-round' => array('group' => 'ion-icon'),
            'ion-podium' => array('group' => 'ion-icon'),
            'ion-pound' => array('group' => 'ion-icon'),
            'ion-power' => array('group' => 'ion-icon'),
            'ion-pricetag' => array('group' => 'ion-icon'),
            'ion-pricetags' => array('group' => 'ion-icon'),
            'ion-printer' => array('group' => 'ion-icon'),
            'ion-pull-request' => array('group' => 'ion-icon'),
            'ion-qr-scanner' => array('group' => 'ion-icon'),
            'ion-quote' => array('group' => 'ion-icon'),
            'ion-radio-waves' => array('group' => 'ion-icon'),
            'ion-record' => array('group' => 'ion-icon'),
            'ion-refresh' => array('group' => 'ion-icon'),
            'ion-reply' => array('group' => 'ion-icon'),
            'ion-reply-all' => array('group' => 'ion-icon'),
            'ion-ribbon-a' => array('group' => 'ion-icon'),
            'ion-ribbon-b' => array('group' => 'ion-icon'),
            'ion-sad' => array('group' => 'ion-icon'),
            'ion-sad-outline' => array('group' => 'ion-icon'),
            'ion-scissors' => array('group' => 'ion-icon'),
            'ion-search' => array('group' => 'ion-icon'),
            'ion-settings' => array('group' => 'ion-icon'),
            'ion-share' => array('group' => 'ion-icon'),
            'ion-shuffle' => array('group' => 'ion-icon'),
            'ion-skip-backward' => array('group' => 'ion-icon'),
            'ion-skip-forward' => array('group' => 'ion-icon'),
            'ion-social-android' => array('group' => 'ion-icon'),
            'ion-social-android-outline' => array('group' => 'ion-icon'),
            'ion-social-angular' => array('group' => 'ion-icon'),
            'ion-social-angular-outline' => array('group' => 'ion-icon'),
            'ion-social-apple' => array('group' => 'ion-icon'),
            'ion-social-apple-outline' => array('group' => 'ion-icon'),
            'ion-social-bitcoin' => array('group' => 'ion-icon'),
            'ion-social-bitcoin-outline' => array('group' => 'ion-icon'),
            'ion-social-buffer' => array('group' => 'ion-icon'),
            'ion-social-buffer-outline' => array('group' => 'ion-icon'),
            'ion-social-chrome' => array('group' => 'ion-icon'),
            'ion-social-chrome-outline' => array('group' => 'ion-icon'),
            'ion-social-codepen' => array('group' => 'ion-icon'),
            'ion-social-codepen-outline' => array('group' => 'ion-icon'),
            'ion-social-css3' => array('group' => 'ion-icon'),
            'ion-social-css3-outline' => array('group' => 'ion-icon'),
            'ion-social-designernews' => array('group' => 'ion-icon'),
            'ion-social-designernews-outline' => array('group' => 'ion-icon'),
            'ion-social-dribbble' => array('group' => 'ion-icon'),
            'ion-social-dribbble-outline' => array('group' => 'ion-icon'),
            'ion-social-dropbox' => array('group' => 'ion-icon'),
            'ion-social-dropbox-outline' => array('group' => 'ion-icon'),
            'ion-social-euro' => array('group' => 'ion-icon'),
            'ion-social-euro-outline' => array('group' => 'ion-icon'),
            'ion-social-facebook' => array('group' => 'ion-icon'),
            'ion-social-facebook-outline' => array('group' => 'ion-icon'),
            'ion-social-foursquare' => array('group' => 'ion-icon'),
            'ion-social-foursquare-outline' => array('group' => 'ion-icon'),
            'ion-social-freebsd-devil' => array('group' => 'ion-icon'),
            'ion-social-github' => array('group' => 'ion-icon'),
            'ion-social-github-outline' => array('group' => 'ion-icon'),
            'ion-social-google' => array('group' => 'ion-icon'),
            'ion-social-google-outline' => array('group' => 'ion-icon'),
            'ion-social-googleplus' => array('group' => 'ion-icon'),
            'ion-social-googleplus-outline' => array('group' => 'ion-icon'),
            'ion-social-hackernews' => array('group' => 'ion-icon'),
            'ion-social-hackernews-outline' => array('group' => 'ion-icon'),
            'ion-social-html5' => array('group' => 'ion-icon'),
            'ion-social-html5-outline' => array('group' => 'ion-icon'),
            'ion-social-instagram' => array('group' => 'ion-icon'),
            'ion-social-instagram-outline' => array('group' => 'ion-icon'),
            'ion-social-javascript' => array('group' => 'ion-icon'),
            'ion-social-javascript-outline' => array('group' => 'ion-icon'),
            'ion-social-linkedin' => array('group' => 'ion-icon'),
            'ion-social-linkedin-outline' => array('group' => 'ion-icon'),
            'ion-social-markdown' => array('group' => 'ion-icon'),
            'ion-social-nodejs' => array('group' => 'ion-icon'),
            'ion-social-octocat' => array('group' => 'ion-icon'),
            'ion-social-pinterest' => array('group' => 'ion-icon'),
            'ion-social-pinterest-outline' => array('group' => 'ion-icon'),
            'ion-social-python' => array('group' => 'ion-icon'),
            'ion-social-reddit' => array('group' => 'ion-icon'),
            'ion-social-reddit-outline' => array('group' => 'ion-icon'),
            'ion-social-rss' => array('group' => 'ion-icon'),
            'ion-social-rss-outline' => array('group' => 'ion-icon'),
            'ion-social-sass' => array('group' => 'ion-icon'),
            'ion-social-skype' => array('group' => 'ion-icon'),
            'ion-social-skype-outline' => array('group' => 'ion-icon'),
            'ion-social-snapchat' => array('group' => 'ion-icon'),
            'ion-social-snapchat-outline' => array('group' => 'ion-icon'),
            'ion-social-tumblr' => array('group' => 'ion-icon'),
            'ion-social-tumblr-outline' => array('group' => 'ion-icon'),
            'ion-social-tux' => array('group' => 'ion-icon'),
            'ion-social-twitch' => array('group' => 'ion-icon'),
            'ion-social-twitch-outline' => array('group' => 'ion-icon'),
            'ion-social-twitter' => array('group' => 'ion-icon'),
            'ion-social-twitter-outline' => array('group' => 'ion-icon'),
            'ion-social-usd' => array('group' => 'ion-icon'),
            'ion-social-usd-outline' => array('group' => 'ion-icon'),
            'ion-social-vimeo' => array('group' => 'ion-icon'),
            'ion-social-vimeo-outline' => array('group' => 'ion-icon'),
            'ion-social-whatsapp' => array('group' => 'ion-icon'),
            'ion-social-whatsapp-outline' => array('group' => 'ion-icon'),
            'ion-social-windows' => array('group' => 'ion-icon'),
            'ion-social-windows-outline' => array('group' => 'ion-icon'),
            'ion-social-wordpress' => array('group' => 'ion-icon'),
            'ion-social-wordpress-outline' => array('group' => 'ion-icon'),
            'ion-social-yahoo' => array('group' => 'ion-icon'),
            'ion-social-yahoo-outline' => array('group' => 'ion-icon'),
            'ion-social-yen' => array('group' => 'ion-icon'),
            'ion-social-yen-outline' => array('group' => 'ion-icon'),
            'ion-social-youtube' => array('group' => 'ion-icon'),
            'ion-social-youtube-outline' => array('group' => 'ion-icon'),
            'ion-soup-can' => array('group' => 'ion-icon'),
            'ion-soup-can-outline' => array('group' => 'ion-icon'),
            'ion-speakerphone' => array('group' => 'ion-icon'),
            'ion-speedometer' => array('group' => 'ion-icon'),
            'ion-spoon' => array('group' => 'ion-icon'),
            'ion-star' => array('group' => 'ion-icon'),
            'ion-stats-bars' => array('group' => 'ion-icon'),
            'ion-steam' => array('group' => 'ion-icon'),
            'ion-stop' => array('group' => 'ion-icon'),
            'ion-thermometer' => array('group' => 'ion-icon'),
            'ion-thumbsdown' => array('group' => 'ion-icon'),
            'ion-thumbsup' => array('group' => 'ion-icon'),
            'ion-toggle' => array('group' => 'ion-icon'),
            'ion-toggle-filled' => array('group' => 'ion-icon'),
            'ion-transgender' => array('group' => 'ion-icon'),
            'ion-trash-a' => array('group' => 'ion-icon'),
            'ion-trash-b' => array('group' => 'ion-icon'),
            'ion-trophy' => array('group' => 'ion-icon'),
            'ion-tshirt' => array('group' => 'ion-icon'),
            'ion-tshirt-outline' => array('group' => 'ion-icon'),
            'ion-umbrella' => array('group' => 'ion-icon'),
            'ion-university' => array('group' => 'ion-icon'),
            'ion-unlocked' => array('group' => 'ion-icon'),
            'ion-upload' => array('group' => 'ion-icon'),
            'ion-usb' => array('group' => 'ion-icon'),
            'ion-videocamera' => array('group' => 'ion-icon'),
            'ion-volume-high' => array('group' => 'ion-icon'),
            'ion-volume-low' => array('group' => 'ion-icon'),
            'ion-volume-medium' => array('group' => 'ion-icon'),
            'ion-volume-mute' => array('group' => 'ion-icon'),
            'ion-wand' => array('group' => 'ion-icon'),
            'ion-waterdrop' => array('group' => 'ion-icon'),
            'ion-wifi' => array('group' => 'ion-icon'),
            'ion-wineglass' => array('group' => 'ion-icon'),
            'ion-woman' => array('group' => 'ion-icon'),
            'ion-wrench' => array('group' => 'ion-icon'),
            'ion-xbox' => array('group' => 'ion-icon'),

            // Web Application Icons
            'fa fa-adjust' => array('group' => 'web-app'),
            'fa fa-anchor' => array('group' => 'web-app'),
            'fa fa-archive' => array('group' => 'web-app'),
            'fa fa-area-chart' => array('group' => 'web-app'),
            'fa fa-arrows' => array('group' => 'web-app'),
            'fa fa-arrows-h' => array('group' => 'web-app'),
            'fa fa-arrows-v' => array('group' => 'web-app'),
            'fa fa-asterisk' => array('group' => 'web-app'),
            'fa fa-at' => array('group' => 'web-app'),
            'fa fa-ban' => array('group' => 'web-app'),
            'fa fa-bar-chart' => array('group' => 'web-app'),
            'fa fa-barcode' => array('group' => 'web-app'),
            'fa fa-bars' => array('group' => 'web-app'),
            'fa fa-bed' => array('group' => 'web-app'),
            'fa fa-beer' => array('group' => 'web-app'),
            'fa fa-bell' => array('group' => 'web-app'),
            'fa fa-bell-o' => array('group' => 'web-app'),
            'fa fa-bell-slash' => array('group' => 'web-app'),
            'fa fa-bell-slash-o' => array('group' => 'web-app'),
            'fa fa-bicycle' => array('group' => 'web-app'),
            'fa fa-binoculars' => array('group' => 'web-app'),
            'fa fa-birthday-cake' => array('group' => 'web-app'),
            'fa fa-bolt' => array('group' => 'web-app'),
            'fa fa-bomb' => array('group' => 'web-app'),
            'fa fa-book' => array('group' => 'web-app'),
            'fa fa-bookmark' => array('group' => 'web-app'),
            'fa fa-bookmark-o' => array('group' => 'web-app'),
            'fa fa-briefcase' => array('group' => 'web-app'),
            'fa fa-bug' => array('group' => 'web-app'),
            'fa fa-building' => array('group' => 'web-app'),
            'fa fa-building-o' => array('group' => 'web-app'),
            'fa fa-bullhorn' => array('group' => 'web-app'),
            'fa fa-bullseye' => array('group' => 'web-app'),
            'fa fa-bus' => array('group' => 'web-app'),
            'fa fa-calculator' => array('group' => 'web-app'),
            'fa fa-calendar' => array('group' => 'web-app'),
            'fa fa-calendar-o' => array('group' => 'web-app'),
            'fa fa-camera' => array('group' => 'web-app'),
            'fa fa-camera-retro' => array('group' => 'web-app'),
            'fa fa-car' => array('group' => 'web-app'),
            'fa fa-caret-square-o-down' => array('group' => 'web-app'),
            'fa fa-caret-square-o-left' => array('group' => 'web-app'),
            'fa fa-caret-square-o-right' => array('group' => 'web-app'),
            'fa fa-caret-square-o-up' => array('group' => 'web-app'),
            'fa fa-cart-arrow-down' => array('group' => 'web-app'),
            'fa fa-cart-plus' => array('group' => 'web-app'),
            'fa fa-cc' => array('group' => 'web-app'),
            'fa fa-certificate' => array('group' => 'web-app'),
            'fa fa-check' => array('group' => 'web-app'),
            'fa fa-check-circle' => array('group' => 'web-app'),
            'fa fa-check-circle-o' => array('group' => 'web-app'),
            'fa fa-check-square' => array('group' => 'web-app'),
            'fa fa-check-square-o' => array('group' => 'web-app'),
            'fa fa-child' => array('group' => 'web-app'),
            'fa fa-circle' => array('group' => 'web-app'),
            'fa fa-circle-o' => array('group' => 'web-app'),
            'fa fa-circle-o-notch' => array('group' => 'web-app'),
            'fa fa-circle-thin' => array('group' => 'web-app'),
            'fa fa-clock-o' => array('group' => 'web-app'),
            'fa fa-cloud' => array('group' => 'web-app'),
            'fa fa-cloud-download' => array('group' => 'web-app'),
            'fa fa-cloud-upload' => array('group' => 'web-app'),
            'fa fa-code' => array('group' => 'web-app'),
            'fa fa-code-fork' => array('group' => 'web-app'),
            'fa fa-coffee' => array('group' => 'web-app'),
            'fa fa-cog' => array('group' => 'web-app'),
            'fa fa-cogs' => array('group' => 'web-app'),
            'fa fa-comment' => array('group' => 'web-app'),
            'fa fa-comment-o' => array('group' => 'web-app'),
            'fa fa-comments' => array('group' => 'web-app'),
            'fa fa-comments-o' => array('group' => 'web-app'),
            'fa fa-compass' => array('group' => 'web-app'),
            'fa fa-copyright' => array('group' => 'web-app'),
            'fa fa-credit-card' => array('group' => 'web-app'),
            'fa fa-crop' => array('group' => 'web-app'),
            'fa fa-crosshairs' => array('group' => 'web-app'),
            'fa fa-cube' => array('group' => 'web-app'),
            'fa fa-cubes' => array('group' => 'web-app'),
            'fa fa-cutlery' => array('group' => 'web-app'),
            'fa fa-database' => array('group' => 'web-app'),
            'fa fa-desktop' => array('group' => 'web-app'),
            'fa fa-diamond' => array('group' => 'web-app'),
            'fa fa-dot-circle-o' => array('group' => 'web-app'),
            'fa fa-download' => array('group' => 'web-app'),
            'fa fa-ellipsis-h' => array('group' => 'web-app'),
            'fa fa-ellipsis-v' => array('group' => 'web-app'),
            'fa fa-envelope' => array('group' => 'web-app'),
            'fa fa-envelope-o' => array('group' => 'web-app'),
            'fa fa-envelope-square' => array('group' => 'web-app'),
            'fa fa-eraser' => array('group' => 'web-app'),
            'fa fa-exchange' => array('group' => 'web-app'),
            'fa fa-exclamation' => array('group' => 'web-app'),
            'fa fa-exclamation-circle' => array('group' => 'web-app'),
            'fa fa-exclamation-triangle' => array('group' => 'web-app'),
            'fa fa-external-link' => array('group' => 'web-app'),
            'fa fa-external-link-square' => array('group' => 'web-app'),
            'fa fa-eye' => array('group' => 'web-app'),
            'fa fa-eye-slash' => array('group' => 'web-app'),
            'fa fa-eyedropper' => array('group' => 'web-app'),
            'fa fa-fax' => array('group' => 'web-app'),
            'fa fa-female' => array('group' => 'web-app'),
            'fa fa-fighter-jet' => array('group' => 'web-app'),
            'fa fa-file-archive-o' => array('group' => 'web-app'),
            'fa fa-file-audio-o' => array('group' => 'web-app'),
            'fa fa-file-code-o' => array('group' => 'web-app'),
            'fa fa-file-excel-o' => array('group' => 'web-app'),
            'fa fa-file-image-o' => array('group' => 'web-app'),
            'fa fa-file-pdf-o' => array('group' => 'web-app'),
            'fa fa-file-powerpoint-o' => array('group' => 'web-app'),
            'fa fa-file-video-o' => array('group' => 'web-app'),
            'fa fa-file-word-o' => array('group' => 'web-app'),
            'fa fa-film' => array('group' => 'web-app'),
            'fa fa-filter' => array('group' => 'web-app'),
            'fa fa-fire' => array('group' => 'web-app'),
            'fa fa-fire-extinguisher' => array('group' => 'web-app'),
            'fa fa-flag' => array('group' => 'web-app'),
            'fa fa-flag-checkered' => array('group' => 'web-app'),
            'fa fa-flag-o' => array('group' => 'web-app'),
            'fa fa-flask' => array('group' => 'web-app'),
            'fa fa-folder' => array('group' => 'web-app'),
            'fa fa-folder-o' => array('group' => 'web-app'),
            'fa fa-folder-open' => array('group' => 'web-app'),
            'fa fa-folder-open-o' => array('group' => 'web-app'),
            'fa fa-frown-o' => array('group' => 'web-app'),
            'fa fa-futbol-o' => array('group' => 'web-app'),
            'fa fa-gamepad' => array('group' => 'web-app'),
            'fa fa-gavel' => array('group' => 'web-app'),
            'fa fa-gift' => array('group' => 'web-app'),
            'fa fa-glass' => array('group' => 'web-app'),
            'fa fa-globe' => array('group' => 'web-app'),
            'fa fa-graduation-cap' => array('group' => 'web-app'),
            'fa fa-hdd-o' => array('group' => 'web-app'),
            'fa fa-headphones' => array('group' => 'web-app'),
            'fa fa-heart' => array('group' => 'web-app'),
            'fa fa-heart-o' => array('group' => 'web-app'),
            'fa fa-heartbeat' => array('group' => 'web-app'),
            'fa fa-history' => array('group' => 'web-app'),
            'fa fa-home' => array('group' => 'web-app'),
            'fa fa-inbox' => array('group' => 'web-app'),
            'fa fa-info' => array('group' => 'web-app'),
            'fa fa-info-circle' => array('group' => 'web-app'),
            'fa fa-key' => array('group' => 'web-app'),
            'fa fa-keyboard-o' => array('group' => 'web-app'),
            'fa fa-language' => array('group' => 'web-app'),
            'fa fa-laptop' => array('group' => 'web-app'),
            'fa fa-leaf' => array('group' => 'web-app'),
            'fa fa-lemon-o' => array('group' => 'web-app'),
            'fa fa-level-down' => array('group' => 'web-app'),
            'fa fa-level-up' => array('group' => 'web-app'),
            'fa fa-life-ring' => array('group' => 'web-app'),
            'fa fa-lightbulb-o' => array('group' => 'web-app'),
            'fa fa-line-chart' => array('group' => 'web-app'),
            'fa fa-location-arrow' => array('group' => 'web-app'),
            'fa fa-lock' => array('group' => 'web-app'),
            'fa fa-magic' => array('group' => 'web-app'),
            'fa fa-magnet' => array('group' => 'web-app'),
            'fa fa-male' => array('group' => 'web-app'),
            'fa fa-map-marker' => array('group' => 'web-app'),
            'fa fa-meh-o' => array('group' => 'web-app'),
            'fa fa-microphone' => array('group' => 'web-app'),
            'fa fa-microphone-slash' => array('group' => 'web-app'),
            'fa fa-minus' => array('group' => 'web-app'),
            'fa fa-minus-circle' => array('group' => 'web-app'),
            'fa fa-minus-square' => array('group' => 'web-app'),
            'fa fa-minus-square-o' => array('group' => 'web-app'),
            'fa fa-mobile' => array('group' => 'web-app'),
            'fa fa-money' => array('group' => 'web-app'),
            'fa fa-moon-o' => array('group' => 'web-app'),
            'fa fa-motorcycle' => array('group' => 'web-app'),
            'fa fa-music' => array('group' => 'web-app'),
            'fa fa-newspaper-o' => array('group' => 'web-app'),
            'fa fa-paint-brush' => array('group' => 'web-app'),
            'fa fa-paper-plane' => array('group' => 'web-app'),
            'fa fa-paper-plane-o' => array('group' => 'web-app'),
            'fa fa-paw' => array('group' => 'web-app'),
            'fa fa-pencil' => array('group' => 'web-app'),
            'fa fa-pencil-square' => array('group' => 'web-app'),
            'fa fa-pencil-square-o' => array('group' => 'web-app'),
            'fa fa-phone' => array('group' => 'web-app'),
            'fa fa-phone-square' => array('group' => 'web-app'),
            'fa fa-picture-o' => array('group' => 'web-app'),
            'fa fa-pie-chart' => array('group' => 'web-app'),
            'fa fa-plane' => array('group' => 'web-app'),
            'fa fa-plug' => array('group' => 'web-app'),
            'fa fa-plus' => array('group' => 'web-app'),
            'fa fa-plus-circle' => array('group' => 'web-app'),
            'fa fa-plus-square' => array('group' => 'web-app'),
            'fa fa-plus-square-o' => array('group' => 'web-app'),
            'fa fa-power-off' => array('group' => 'web-app'),
            'fa fa-print' => array('group' => 'web-app'),
            'fa fa-puzzle-piece' => array('group' => 'web-app'),
            'fa fa-qrcode' => array('group' => 'web-app'),
            'fa fa-question' => array('group' => 'web-app'),
            'fa fa-question-circle' => array('group' => 'web-app'),
            'fa fa-quote-left' => array('group' => 'web-app'),
            'fa fa-quote-right' => array('group' => 'web-app'),
            'fa fa-random' => array('group' => 'web-app'),
            'fa fa-recycle' => array('group' => 'web-app'),
            'fa fa-refresh' => array('group' => 'web-app'),
            'fa fa-reply' => array('group' => 'web-app'),
            'fa fa-reply-all' => array('group' => 'web-app'),
            'fa fa-retweet' => array('group' => 'web-app'),
            'fa fa-road' => array('group' => 'web-app'),
            'fa fa-rocket' => array('group' => 'web-app'),
            'fa fa-rss' => array('group' => 'web-app'),
            'fa fa-rss-square' => array('group' => 'web-app'),
            'fa fa-search' => array('group' => 'web-app'),
            'fa fa-search-minus' => array('group' => 'web-app'),
            'fa fa-search-plus' => array('group' => 'web-app'),
            'fa fa-server' => array('group' => 'web-app'),
            'fa fa-share' => array('group' => 'web-app'),
            'fa fa-share-alt' => array('group' => 'web-app'),
            'fa fa-share-alt-square' => array('group' => 'web-app'),
            'fa fa-share-square' => array('group' => 'web-app'),
            'fa fa-share-square-o' => array('group' => 'web-app'),
            'fa fa-shield' => array('group' => 'web-app'),
            'fa fa-ship' => array('group' => 'web-app'),
            'fa fa-shopping-cart' => array('group' => 'web-app'),
            'fa fa-sign-in' => array('group' => 'web-app'),
            'fa fa-sign-out' => array('group' => 'web-app'),
            'fa fa-signal' => array('group' => 'web-app'),
            'fa fa-sitemap' => array('group' => 'web-app'),
            'fa fa-sliders' => array('group' => 'web-app'),
            'fa fa-smile-o' => array('group' => 'web-app'),
            'fa fa-sort' => array('group' => 'web-app'),
            'fa fa-sort-alpha-asc' => array('group' => 'web-app'),
            'fa fa-sort-alpha-desc' => array('group' => 'web-app'),
            'fa fa-sort-amount-asc' => array('group' => 'web-app'),
            'fa fa-sort-amount-desc' => array('group' => 'web-app'),
            'fa fa-sort-asc' => array('group' => 'web-app'),
            'fa fa-sort-desc' => array('group' => 'web-app'),
            'fa fa-sort-numeric-asc' => array('group' => 'web-app'),
            'fa fa-sort-numeric-desc' => array('group' => 'web-app'),
            'fa fa-space-shuttle' => array('group' => 'web-app'),
            'fa fa-spinner' => array('group' => 'web-app'),
            'fa fa-spoon' => array('group' => 'web-app'),
            'fa fa-square' => array('group' => 'web-app'),
            'fa fa-square-o' => array('group' => 'web-app'),
            'fa fa-star' => array('group' => 'web-app'),
            'fa fa-star-half' => array('group' => 'web-app'),
            'fa fa-star-half-o' => array('group' => 'web-app'),
            'fa fa-star-o' => array('group' => 'web-app'),
            'fa fa-street-view' => array('group' => 'web-app'),
            'fa fa-suitcase' => array('group' => 'web-app'),
            'fa fa-sun-o' => array('group' => 'web-app'),
            'fa fa-tablet' => array('group' => 'web-app'),
            'fa fa-tachometer' => array('group' => 'web-app'),
            'fa fa-tag' => array('group' => 'web-app'),
            'fa fa-tags' => array('group' => 'web-app'),
            'fa fa-tasks' => array('group' => 'web-app'),
            'fa fa-taxi' => array('group' => 'web-app'),
            'fa fa-terminal' => array('group' => 'web-app'),
            'fa fa-thumb-tack' => array('group' => 'web-app'),
            'fa fa-thumbs-down' => array('group' => 'web-app'),
            'fa fa-thumbs-o-down' => array('group' => 'web-app'),
            'fa fa-thumbs-o-up' => array('group' => 'web-app'),
            'fa fa-thumbs-up' => array('group' => 'web-app'),
            'fa fa-ticket' => array('group' => 'web-app'),
            'fa fa-times' => array('group' => 'web-app'),
            'fa fa-times-circle' => array('group' => 'web-app'),
            'fa fa-times-circle-o' => array('group' => 'web-app'),
            'fa fa-tint' => array('group' => 'web-app'),
            'fa fa-toggle-off' => array('group' => 'web-app'),
            'fa fa-toggle-on' => array('group' => 'web-app'),
            'fa fa-trash' => array('group' => 'web-app'),
            'fa fa-trash-o' => array('group' => 'web-app'),
            'fa fa-tree' => array('group' => 'web-app'),
            'fa fa-trophy' => array('group' => 'web-app'),
            'fa fa-truck' => array('group' => 'web-app'),
            'fa fa-tty' => array('group' => 'web-app'),
            'fa fa-umbrella' => array('group' => 'web-app'),
            'fa fa-university' => array('group' => 'web-app'),
            'fa fa-unlock' => array('group' => 'web-app'),
            'fa fa-unlock-alt' => array('group' => 'web-app'),
            'fa fa-upload' => array('group' => 'web-app'),
            'fa fa-user' => array('group' => 'web-app'),
            'fa fa-user-plus' => array('group' => 'web-app'),
            'fa fa-user-secret' => array('group' => 'web-app'),
            'fa fa-user-times' => array('group' => 'web-app'),
            'fa fa-users' => array('group' => 'web-app'),
            'fa fa-video-camera' => array('group' => 'web-app'),
            'fa fa-volume-down' => array('group' => 'web-app'),
            'fa fa-volume-off' => array('group' => 'web-app'),
            'fa fa-volume-up' => array('group' => 'web-app'),
            'fa fa-wheelchair' => array('group' => 'web-app'),
            'fa fa-wifi' => array('group' => 'web-app'),
            'fa fa-wrench' => array('group' => 'web-app'),
            // Transportation Icons
            'fa fa-ambulance' => array('group' => 'transport'),
            'fa fa-bicycle' => array('group' => 'transport'),
            'fa fa-bus' => array('group' => 'transport'),
            'fa fa-car' => array('group' => 'transport'),
            'fa fa-fighter-jet' => array('group' => 'transport'),
            'fa fa-motorcycle' => array('group' => 'transport'),
            'fa fa-plane' => array('group' => 'transport'),
            'fa fa-rocket' => array('group' => 'transport'),
            'fa fa-ship' => array('group' => 'transport'),
            'fa fa-space-shuttle' => array('group' => 'transport'),
            'fa fa-subway' => array('group' => 'transport'),
            'fa fa-taxi' => array('group' => 'transport'),
            'fa fa-train' => array('group' => 'transport'),
            'fa fa-truck' => array('group' => 'transport'),
            'fa fa-wheelchair' => array('group' => 'transport'),
            // Gender Icons
            'fa fa-circle-thin' => array('group' => 'gender'),
            'fa fa-mars' => array('group' => 'gender'),
            'fa fa-mars-double' => array('group' => 'gender'),
            'fa fa-mars-stroke' => array('group' => 'gender'),
            'fa fa-mars-stroke-h' => array('group' => 'gender'),
            'fa fa-mars-stroke-v' => array('group' => 'gender'),
            'fa fa-mercury' => array('group' => 'gender'),
            'fa fa-neuter' => array('group' => 'gender'),
            'fa fa-transgender' => array('group' => 'gender'),
            'fa fa-transgender-alt' => array('group' => 'gender'),
            'fa fa-venus' => array('group' => 'gender'),
            'fa fa-venus-double' => array('group' => 'gender'),
            'fa fa-venus-mars' => array('group' => 'gender'),
            // File Type Icons
            'fa fa-file' => array('group' => 'file'),
            'fa fa-file-archive-o' => array('group' => 'file'),
            'fa fa-file-audio-o' => array('group' => 'file'),
            'fa fa-file-code-o' => array('group' => 'file'),
            'fa fa-file-excel-o' => array('group' => 'file'),
            'fa fa-file-image-o' => array('group' => 'file'),
            'fa fa-file-o' => array('group' => 'file'),
            'fa fa-file-pdf-o' => array('group' => 'file'),
            'fa fa-file-powerpoint-o' => array('group' => 'file'),
            'fa fa-file-text' => array('group' => 'file'),
            'fa fa-file-text-o' => array('group' => 'file'),
            'fa fa-file-video-o' => array('group' => 'file'),
            'fa fa-file-word-o' => array('group' => 'file'),
            // FIXME There is need for changing HTML/CSS for spinner to work properly
            //
            // Spinner Icons
            // 'fa fa-spin fa-circle-o-notch' => array('group' => 'spinner'),
            // 'fa fa-spin fa-cog' => array('group' => 'spinner'),
            // 'fa fa-spin fa-refresh' => array('group' => 'spinner'),
            // 'fa fa-spin fa-spinner' => array('group' => 'spinner'),
            // Form Control Icons
            'fa fa-check-square' => array('group' => 'form'),
            'fa fa-check-square-o' => array('group' => 'form'),
            'fa fa-circle' => array('group' => 'form'),
            'fa fa-circle-o' => array('group' => 'form'),
            'fa fa-dot-circle-o' => array('group' => 'form'),
            'fa fa-minus-square' => array('group' => 'form'),
            'fa fa-minus-square-o' => array('group' => 'form'),
            'fa fa-plus-square' => array('group' => 'form'),
            'fa fa-plus-square-o' => array('group' => 'form'),
            'fa fa-square' => array('group' => 'form'),
            'fa fa-square-o' => array('group' => 'form'),
            // Payment Icons
            'fa fa-cc-amex' => array('group' => 'payment'),
            'fa fa-cc-discover' => array('group' => 'payment'),
            'fa fa-cc-mastercard' => array('group' => 'payment'),
            'fa fa-cc-paypal' => array('group' => 'payment'),
            'fa fa-cc-stripe' => array('group' => 'payment'),
            'fa fa-cc-visa' => array('group' => 'payment'),
            'fa fa-credit-card' => array('group' => 'payment'),
            'fa fa-google-wallet' => array('group' => 'payment'),
            'fa fa-paypal' => array('group' => 'payment'),
            // Chart Icons
            'fa fa-area-chart' => array('group' => 'chart'),
            'fa fa-bar-chart' => array('group' => 'chart'),
            'fa fa-line-chart' => array('group' => 'chart'),
            'fa fa-pie-chart' => array('group' => 'chart'),
            // Currency Icons
            'fa fa-btc' => array('group' => 'currency'),
            'fa fa-eur' => array('group' => 'currency'),
            'fa fa-gbp' => array('group' => 'currency'),
            'fa fa-ils' => array('group' => 'currency'),
            'fa fa-inr' => array('group' => 'currency'),
            'fa fa-jpy' => array('group' => 'currency'),
            'fa fa-krw' => array('group' => 'currency'),
            'fa fa-money' => array('group' => 'currency'),
            'fa fa-rub' => array('group' => 'currency'),
            'fa fa-try' => array('group' => 'currency'),
            'fa fa-usd' => array('group' => 'currency'),
            // Text Editor Icons
            'fa fa-align-center' => array('group' => 'text'),
            'fa fa-align-justify' => array('group' => 'text'),
            'fa fa-align-left' => array('group' => 'text'),
            'fa fa-align-right' => array('group' => 'text'),
            'fa fa-bold' => array('group' => 'text'),
            'fa fa-chain-broken' => array('group' => 'text'),
            'fa fa-clipboard' => array('group' => 'text'),
            'fa fa-columns' => array('group' => 'text'),
            'fa fa-eraser' => array('group' => 'text'),
            'fa fa-file' => array('group' => 'text'),
            'fa fa-file-o' => array('group' => 'text'),
            'fa fa-file-text' => array('group' => 'text'),
            'fa fa-file-text-o' => array('group' => 'text'),
            'fa fa-files-o' => array('group' => 'text'),
            'fa fa-floppy-o' => array('group' => 'text'),
            'fa fa-font' => array('group' => 'text'),
            'fa fa-header' => array('group' => 'text'),
            'fa fa-indent' => array('group' => 'text'),
            'fa fa-italic' => array('group' => 'text'),
            'fa fa-link' => array('group' => 'text'),
            'fa fa-list' => array('group' => 'text'),
            'fa fa-list-alt' => array('group' => 'text'),
            'fa fa-list-ol' => array('group' => 'text'),
            'fa fa-list-ul' => array('group' => 'text'),
            'fa fa-outdent' => array('group' => 'text'),
            'fa fa-paperclip' => array('group' => 'text'),
            'fa fa-paragraph' => array('group' => 'text'),
            'fa fa-repeat' => array('group' => 'text'),
            'fa fa-scissors' => array('group' => 'text'),
            'fa fa-strikethrough' => array('group' => 'text'),
            'fa fa-subscript' => array('group' => 'text'),
            'fa fa-superscript' => array('group' => 'text'),
            'fa fa-table' => array('group' => 'text'),
            'fa fa-text-height' => array('group' => 'text'),
            'fa fa-text-width' => array('group' => 'text'),
            'fa fa-th' => array('group' => 'text'),
            'fa fa-th-large' => array('group' => 'text'),
            'fa fa-th-list' => array('group' => 'text'),
            'fa fa-underline' => array('group' => 'text'),
            'fa fa-undo' => array('group' => 'text'),
            // Directional Icons
            'fa fa-angle-double-down' => array('group' => 'direction'),
            'fa fa-angle-double-left' => array('group' => 'direction'),
            'fa fa-angle-double-right' => array('group' => 'direction'),
            'fa fa-angle-double-up' => array('group' => 'direction'),
            'fa fa-angle-down' => array('group' => 'direction'),
            'fa fa-angle-left' => array('group' => 'direction'),
            'fa fa-angle-right' => array('group' => 'direction'),
            'fa fa-angle-up' => array('group' => 'direction'),
            'fa fa-arrow-circle-down' => array('group' => 'direction'),
            'fa fa-arrow-circle-left' => array('group' => 'direction'),
            'fa fa-arrow-circle-o-down' => array('group' => 'direction'),
            'fa fa-arrow-circle-o-left' => array('group' => 'direction'),
            'fa fa-arrow-circle-o-right' => array('group' => 'direction'),
            'fa fa-arrow-circle-o-up' => array('group' => 'direction'),
            'fa fa-arrow-circle-right' => array('group' => 'direction'),
            'fa fa-arrow-circle-up' => array('group' => 'direction'),
            'fa fa-arrow-down' => array('group' => 'direction'),
            'fa fa-arrow-left' => array('group' => 'direction'),
            'fa fa-arrow-right' => array('group' => 'direction'),
            'fa fa-arrow-up' => array('group' => 'direction'),
            'fa fa-arrows' => array('group' => 'direction'),
            'fa fa-arrows-alt' => array('group' => 'direction'),
            'fa fa-arrows-h' => array('group' => 'direction'),
            'fa fa-arrows-v' => array('group' => 'direction'),
            'fa fa-caret-down' => array('group' => 'direction'),
            'fa fa-caret-left' => array('group' => 'direction'),
            'fa fa-caret-right' => array('group' => 'direction'),
            'fa fa-caret-square-o-down' => array('group' => 'direction'),
            'fa fa-caret-square-o-left' => array('group' => 'direction'),
            'fa fa-caret-square-o-right' => array('group' => 'direction'),
            'fa fa-caret-square-o-up' => array('group' => 'direction'),
            'fa fa-caret-up' => array('group' => 'direction'),
            'fa fa-chevron-circle-down' => array('group' => 'direction'),
            'fa fa-chevron-circle-left' => array('group' => 'direction'),
            'fa fa-chevron-circle-right' => array('group' => 'direction'),
            'fa fa-chevron-circle-up' => array('group' => 'direction'),
            'fa fa-chevron-down' => array('group' => 'direction'),
            'fa fa-chevron-left' => array('group' => 'direction'),
            'fa fa-chevron-right' => array('group' => 'direction'),
            'fa fa-chevron-up' => array('group' => 'direction'),
            'fa fa-hand-o-down' => array('group' => 'direction'),
            'fa fa-hand-o-left' => array('group' => 'direction'),
            'fa fa-hand-o-right' => array('group' => 'direction'),
            'fa fa-hand-o-up' => array('group' => 'direction'),
            'fa fa-long-arrow-down' => array('group' => 'direction'),
            'fa fa-long-arrow-left' => array('group' => 'direction'),
            'fa fa-long-arrow-right' => array('group' => 'direction'),
            'fa fa-long-arrow-up' => array('group' => 'direction'),
            // Video Player Icons
            'fa fa-arrows-alt' => array('group' => 'video'),
            'fa fa-backward' => array('group' => 'video'),
            'fa fa-compress' => array('group' => 'video'),
            'fa fa-eject' => array('group' => 'video'),
            'fa fa-expand' => array('group' => 'video'),
            'fa fa-fast-backward' => array('group' => 'video'),
            'fa fa-fast-forward' => array('group' => 'video'),
            'fa fa-forward' => array('group' => 'video'),
            'fa fa-pause' => array('group' => 'video'),
            'fa fa-play' => array('group' => 'video'),
            'fa fa-play-circle' => array('group' => 'video'),
            'fa fa-play-circle-o' => array('group' => 'video'),
            'fa fa-step-backward' => array('group' => 'video'),
            'fa fa-step-forward' => array('group' => 'video'),
            'fa fa-stop' => array('group' => 'video'),
            'fa fa-youtube-play' => array('group' => 'video'),
            // Brand Icons
            'fa fa-adn' => array('group' => 'brand'),
            'fa fa-android' => array('group' => 'brand'),
            'fa fa-angellist' => array('group' => 'brand'),
            'fa fa-apple' => array('group' => 'brand'),
            'fa fa-behance' => array('group' => 'brand'),
            'fa fa-behance-square' => array('group' => 'brand'),
            'fa fa-bitbucket' => array('group' => 'brand'),
            'fa fa-bitbucket-square' => array('group' => 'brand'),
            'fa fa-btc' => array('group' => 'brand'),
            'fa fa-buysellads' => array('group' => 'brand'),
            'fa fa-cc-amex' => array('group' => 'brand'),
            'fa fa-cc-discover' => array('group' => 'brand'),
            'fa fa-cc-mastercard' => array('group' => 'brand'),
            'fa fa-cc-paypal' => array('group' => 'brand'),
            'fa fa-cc-stripe' => array('group' => 'brand'),
            'fa fa-cc-visa' => array('group' => 'brand'),
            'fa fa-codepen' => array('group' => 'brand'),
            'fa fa-connectdevelop' => array('group' => 'brand'),
            'fa fa-css3' => array('group' => 'brand'),
            'fa fa-dashcube' => array('group' => 'brand'),
            'fa fa-delicious' => array('group' => 'brand'),
            'fa fa-deviantart' => array('group' => 'brand'),
            'fa fa-digg' => array('group' => 'brand'),
            'fa fa-dribbble' => array('group' => 'brand'),
            'fa fa-dropbox' => array('group' => 'brand'),
            'fa fa-drupal' => array('group' => 'brand'),
            'fa fa-empire' => array('group' => 'brand'),
            'fa fa-facebook' => array('group' => 'brand'),
            'fa fa-facebook-official' => array('group' => 'brand'),
            'fa fa-facebook-square' => array('group' => 'brand'),
            'fa fa-flickr' => array('group' => 'brand'),
            'fa fa-forumbee' => array('group' => 'brand'),
            'fa fa-foursquare' => array('group' => 'brand'),
            'fa fa-git' => array('group' => 'brand'),
            'fa fa-git-square' => array('group' => 'brand'),
            'fa fa-github' => array('group' => 'brand'),
            'fa fa-github-alt' => array('group' => 'brand'),
            'fa fa-github-square' => array('group' => 'brand'),
            'fa fa-google' => array('group' => 'brand'),
            'fa fa-google-plus' => array('group' => 'brand'),
            'fa fa-google-plus-square' => array('group' => 'brand'),
            'fa fa-google-wallet' => array('group' => 'brand'),
            'fa fa-gratipay' => array('group' => 'brand'),
            'fa fa-hacker-news' => array('group' => 'brand'),
            'fa fa-html5' => array('group' => 'brand'),
            'fa fa-instagram' => array('group' => 'brand'),
            'fa fa-ioxhost' => array('group' => 'brand'),
            'fa fa-joomla' => array('group' => 'brand'),
            'fa fa-jsfiddle' => array('group' => 'brand'),
            'fa fa-lastfm' => array('group' => 'brand'),
            'fa fa-lastfm-square' => array('group' => 'brand'),
            'fa fa-leanpub' => array('group' => 'brand'),
            'fa fa-linkedin' => array('group' => 'brand'),
            'fa fa-linkedin-square' => array('group' => 'brand'),
            'fa fa-linux' => array('group' => 'brand'),
            'fa fa-maxcdn' => array('group' => 'brand'),
            'fa fa-meanpath' => array('group' => 'brand'),
            'fa fa-medium' => array('group' => 'brand'),
            'fa fa-openid' => array('group' => 'brand'),
            'fa fa-pagelines' => array('group' => 'brand'),
            'fa fa-paypal' => array('group' => 'brand'),
            'fa fa-pied-piper' => array('group' => 'brand'),
            'fa fa-pied-piper-alt' => array('group' => 'brand'),
            'fa fa-pinterest' => array('group' => 'brand'),
            'fa fa-pinterest-p' => array('group' => 'brand'),
            'fa fa-pinterest-square' => array('group' => 'brand'),
            'fa fa-qq' => array('group' => 'brand'),
            'fa fa-rebel' => array('group' => 'brand'),
            'fa fa-reddit' => array('group' => 'brand'),
            'fa fa-reddit-square' => array('group' => 'brand'),
            'fa fa-renren' => array('group' => 'brand'),
            'fa fa-sellsy' => array('group' => 'brand'),
            'fa fa-share-alt' => array('group' => 'brand'),
            'fa fa-share-alt-square' => array('group' => 'brand'),
            'fa fa-shirtsinbulk' => array('group' => 'brand'),
            'fa fa-simplybuilt' => array('group' => 'brand'),
            'fa fa-skyatlas' => array('group' => 'brand'),
            'fa fa-skype' => array('group' => 'brand'),
            'fa fa-slack' => array('group' => 'brand'),
            'fa fa-slideshare' => array('group' => 'brand'),
            'fa fa-soundcloud' => array('group' => 'brand'),
            'fa fa-spotify' => array('group' => 'brand'),
            'fa fa-stack-exchange' => array('group' => 'brand'),
            'fa fa-stack-overflow' => array('group' => 'brand'),
            'fa fa-steam' => array('group' => 'brand'),
            'fa fa-steam-square' => array('group' => 'brand'),
            'fa fa-stumbleupon' => array('group' => 'brand'),
            'fa fa-stumbleupon-circle' => array('group' => 'brand'),
            'fa fa-tencent-weibo' => array('group' => 'brand'),
            'fa fa-trello' => array('group' => 'brand'),
            'fa fa-tumblr' => array('group' => 'brand'),
            'fa fa-tumblr-square' => array('group' => 'brand'),
            'fa fa-twitch' => array('group' => 'brand'),
            'fa fa-twitter' => array('group' => 'brand'),
            'fa fa-twitter-square' => array('group' => 'brand'),
            'fa fa-viacoin' => array('group' => 'brand'),
            'fa fa-vimeo-square' => array('group' => 'brand'),
            'fa fa-vine' => array('group' => 'brand'),
            'fa fa-vk' => array('group' => 'brand'),
            'fa fa-weibo' => array('group' => 'brand'),
            'fa fa-weixin' => array('group' => 'brand'),
            'fa fa-whatsapp' => array('group' => 'brand'),
            'fa fa-windows' => array('group' => 'brand'),
            'fa fa-wordpress' => array('group' => 'brand'),
            'fa fa-xing' => array('group' => 'brand'),
            'fa fa-xing-square' => array('group' => 'brand'),
            'fa fa-yahoo' => array('group' => 'brand'),
            'fa fa-yelp' => array('group' => 'brand'),
            'fa fa-youtube' => array('group' => 'brand'),
            'fa fa-youtube-play' => array('group' => 'brand'),
            'fa fa-youtube-square' => array('group' => 'brand'),
            // Medical Icons
            'fa fa-ambulance' => array('group' => 'medical'),
            'fa fa-h-square' => array('group' => 'medical'),
            'fa fa-heart' => array('group' => 'medical'),
            'fa fa-heart-o' => array('group' => 'medical'),
            'fa fa-heartbeat' => array('group' => 'medical'),
            'fa fa-hospital-o' => array('group' => 'medical'),
            'fa fa-medkit' => array('group' => 'medical'),
            'fa fa-plus-square' => array('group' => 'medical'),
            'fa fa-stethoscope' => array('group' => 'medical'),
            'fa fa-user-md' => array('group' => 'medical'),
            'fa fa-wheelchair' => array('group' => 'medical'),
        ),
    );
    return $sets;
}
add_filter('fw_option_type_icon_sets', 'topseo_font_icons');


?>